fedora:
  development: 8984
  test: 8986
localstack:
  development: 200
  test: 400
postgres:
  development: 5433
  test: 5434
redis:
  development: 6380
  test: 6381
solr:
  development: 8983
  test: 8985
